// ui/dom.js

export const dom = {
  authArea: document.getElementById('authArea'),
  loginForm: document.getElementById('loginForm'),
  registerForm: document.getElementById('registerForm'),
  loginEmail: document.getElementById('loginEmail'),
  loginPassword: document.getElementById('loginPassword'),
  registerName: document.getElementById('registerName'),
  registerEmail: document.getElementById('registerEmail'),
  registerPassword: document.getElementById('registerPassword'),
  registerPasswordConfirm: document.getElementById('registerPasswordConfirm'),
  registerModal: document.getElementById('registerModal'),
  registerModalBackdrop: document.getElementById('registerModalBackdrop'),
  closeRegisterModal: document.getElementById('closeRegisterModal'),
  loginStatus: document.getElementById('loginStatus'),
  registerStatus: document.getElementById('registerStatus'),
  showRegister: document.getElementById('showRegister'),
  showLogin: document.getElementById('showLogin'),
  welcomeBox: document.getElementById('welcomeBox'),
  headerWelcomeName: document.getElementById('welcomeNameHeader'),
  headerWelcomeEmail: document.getElementById('welcomeEmailHeader'),
  logoutBtn: document.getElementById('logoutBtn'),
  welcomeArea: document.getElementById('welcomeArea'),
  welcomeName: document.getElementById('welcomeName'),
  welcomeEmail: document.getElementById('welcomeEmail'),
  tabs: document.getElementById('tabs'),
  tabButtons: document.querySelectorAll('.tab-button'),
  tabPanes: document.querySelectorAll('.tab-pane'),

  predictionStatus: document.getElementById('predictionStatus'),

  predictionsContent: document.getElementById('predictionsContent'),
  statsContent: document.getElementById('statsContent'),
  statsStatus: document.getElementById('statsStatus'),
  overviewContent: document.getElementById('overviewContent'),
  overviewStatus: document.getElementById('overviewStatus'),

  predictionsActions: document.querySelector('#predictionsTab .actions'),
  savePredictions: document.getElementById('savePredictions'),
  seasonPicker: document.getElementById('seasonPicker'),
};